FROM python:3.12

WORKDIR /app

COPY ./requirements/base.txt /app/base.txt
COPY ./requirements/api.txt /app/api.txt

RUN pip install --no-cache-dir --upgrade -r /app/base.txt
RUN pip install --no-cache-dir --upgrade -r /app/api.txt

COPY ./common /app/common
COPY ./indexer /app/indexer
COPY ./api /app/api

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "80"]